### ISSUE TITLE
[BE][Epic] Implement Project Proposal Idea APIs

### ISSUE THREAD

**Issue by davorminchorov** [learnhubmkd/api#108]
##  Implement Project Proposal Idea APIs

This ticket is an epic which contains all of the tickets related to project proposal ideas.

- [ ] https://github.com/learnhubmk/api/issues/76
- [ ] https://github.com/learnhubmk/api/issues/77
- [ ] https://github.com/learnhubmk/api/issues/78
- [ ] https://github.com/learnhubmk/api/issues/79
- [ ] https://github.com/learnhubmk/api/issues/80
- [ ] https://github.com/learnhubmk/api/issues/81
- [ ] https://github.com/learnhubmk/api/issues/82
- [ ] https://github.com/learnhubmk/api/issues/83
- [ ] https://github.com/learnhubmk/api/issues/84
- [ ] https://github.com/learnhubmk/api/issues/85
- [ ] https://github.com/learnhubmk/api/issues/86
