### ISSUE TITLE
[BE][Epic] Implement Authentication APIs

### ISSUE THREAD

**Issue by davorminchorov** [learnhubmkd/api#109]
## Authentication APIs

This ticket is an epic which contains all of the tickets related to authentication.

- [x] https://github.com/learnhubmk/api/issues/47
- [x] https://github.com/learnhubmk/api/issues/49
- [x] https://github.com/learnhubmk/api/issues/56
- [x] https://github.com/learnhubmk/api/issues/71
- [x] https://github.com/learnhubmk/api/issues/73
- [x] https://github.com/learnhubmk/api/issues/74
- [x] https://github.com/learnhubmk/api/issues/75
- [x] https://github.com/learnhubmk/api/issues/107
- [x] https://github.com/learnhubmk/api/issues/114
- [x] https://github.com/learnhubmk/api/issues/127
- [x] https://github.com/learnhubmk/api/issues/132
