### ISSUE TITLE
[BE] Content panel and admin panel API endpoint improvements

### ISSUE THREAD

**Issue by davorminchorov** [learnhubmkd/api#158]
### Task description

- [ ] Implement a filter by status parameter to the members, content managers and admin endpoints in the admin panel
- [ ] Implement a `per_page` field to all admin panel index and content panel index API endpoints to make them consistent and make the limit to be 100 max records per page so that the API user cannot send just any number. The default per_page should be 20 records for all index endpoints.
- [ ] Add any missing parameters or fix any examples in the API docs to make it consistent and easy to follow and work with it
- [ ] Regenerate the docs after the changes are done
